**************************************************************************** 
Info        : STEP Reader 
Info        : HyperWorks Version 2024.1.0.30 
Info        : Input file - D:/Data/Unobot_Baby_Bottle/Arm Concept 1.0/FEA L Bracket Arm/L-Bracket_Gripper_Rotation_SM.STEP 
Info        : Translator used - D:/Altair/hwdesktop/io/cn_translators/bin/win64/ct_reader.exe 
Info        : Translation start time - 08-01-2025 16:26:44 
Info        :  
Info        :  
Info        : -------------------------------------------------- 
Info        : Import options selected in HyperMesh 
Info        : -------------------------------------------------- 
Info        :  
Info        :   Command line options 
Info        :   ---------------------- 
Info        :   AvoidPartAttributes               = off 
Info        :   BodyIDAsMetadata                  = off 
Info        :   CleanupTol                        = -0.01 
Info        :   ColorsAsMetadata                  = off 
Info        :   CreationType                      = PackIntoSinglePart 
Info        :   DegSurfTol                        = 0.0 
Info        :   DensityAsMetadata                 = off 
Info        :   DisplayRepresentation             = off 
Info        :   DoNotMergeEdges                   = off 
Info        :   FullNameAsMetadata                = off 
Info        :   ImportBlanked                     = off 
Info        :   ImportCoordinateSystems           = on 
Info        :   ImportFreeCurves                  = on 
Info        :   ImportFreePoints                  = on 
Info        :   LayerAsMetadata                   = off 
Info        :   LegacyHierarchyAsMetadata         = off 
Info        :   MID                               = MaterialId 
Info        :   MaterialName                      = Material 
Info        :   MeshFlag                          = MeshFlag 
Info        :   OriginalIdAsMetadata              = on 
Info        :   PID                               = PID 
Info        :   PartName                          = PartName 
Info        :   PartNumber                        = PartNumber 
Info        :   Revision                          = Revision 
Info        :   ScaleFactor                       = 1.0 
Info        :   SkipCreationOfSolid               = off 
Info        :   SplitComponents                   = Body 
Info        :   StitchingAcrossBodies             = on 
Info        :   TagsAsMetadata                    = on 
Info        :   TargetUnits                       = CAD units 
Info        :   ThicknessName                     = Thickness 
Info        :   UID                               = UID 
Info        :   UpdateSketchingUnits              = on 
Info        :   VariantCondition                  = VariantCondition 
Info        :   VariantScope                      = VariantScope 
Info        :  
Info        :   INI file options 
Info        :   ---------------------- 
Info        :   AvoidThirdPartyConversion         = on 
Info        : -------------------------------------------------- 
Info        :  
Info        : Third party library used - CT Library Version 2022-SP8 
Info        : CT License Key  = altair%0zm50cag0l3r17vw17vw07wp17vw0hp00h7k0hp00hp013ah15hc0gnc0t2l0kgl1dmy15lj07kc15lj0p2b0g6y1cu20ml30p2b0tyu1cu20zm51dmy0tyu1cu2  
Info        : CT License Key Initialization Completed Successfully 
Info        : Reading  D:\Data\Unobot_Baby_Bottle\Arm Concept 1.0\FEA L Bracket Arm\L-Bracket_Gripper_Rotation_SM.STEP 
Info        :  
Info        : Translation end time - 08-01-2025 16:26:51 
Info        : Translation duration - 7.000000 sec 
**************************************************************************** 

 
